spring:
  cloud:
    gateway:
      routes:
        - id: user-consumer
          uri: lb://user-consumer
          predicates:
            - Path=/user/**
        - id: coupon-consumer
          uri: lb://coupon-consumer
          predicates:
            - Path=/coupon/**
        - id: order-route-proxy
          uri: lb://order-consumer
          predicates:
            - Path=/order/**
        - id: chat-route-proxy
          uri: lb://chat-consumer
          predicates:
            - Path=/chat/**
        - id: ohouse-route-proxy
          uri: lb://order-consumer
          predicates:
            - Path=/ohouse/**
  redis:
    database: 0
    host: 192.168.2.171
    port: 6379

