spring:
  cloud:
    gateway:
      routes:
        - id: user-consumer
          uri: lb://user-consumer
          predicates:
            - Path=/user/**
  redis:
    database: 0
    host: 192.168.0.15
    port: 6379

